package com.v2soft.training.model;
// Generated Oct 16, 2019 11:18:55 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EmployeeLogin generated by hbm2java
 */
@Entity
@Table(name = "employee_login", catalog = "employee", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class EmployeeLogin implements java.io.Serializable {

	private EmployeeLoginId id;
	private Employee employeeInfo;
	private String password;
	private Set<LoginSession> loginSessions = new HashSet<LoginSession>(0);

	public EmployeeLogin() {
	}

	public EmployeeLogin(EmployeeLoginId id, Employee employeeInfo, String password) {
		this.id = id;
		this.employeeInfo = employeeInfo;
		this.password = password;
	}

	public EmployeeLogin(EmployeeLoginId id, Employee employeeInfo, String password,
			Set<LoginSession> loginSessions) {
		this.id = id;
		this.employeeInfo = employeeInfo;
		this.password = password;
		this.loginSessions = loginSessions;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "username", column = @Column(name = "username", unique = true, nullable = false, length = 50)),
			@AttributeOverride(name = "employeeId", column = @Column(name = "employee_id", nullable = false, length = 50)) })
	public EmployeeLoginId getId() {
		return this.id;
	}

	public void setId(EmployeeLoginId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id", nullable = false, insertable = false, updatable = false)
	public Employee getEmployeeInfo() {
		return this.employeeInfo;
	}

	public void setEmployeeInfo(Employee employeeInfo) {
		this.employeeInfo = employeeInfo;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeLogin")
	public Set<LoginSession> getLoginSessions() {
		return this.loginSessions;
	}

	public void setLoginSessions(Set<LoginSession> loginSessions) {
		this.loginSessions = loginSessions;
	}

}
