package com.v2soft.training.model;
// Generated Oct 16, 2019 11:18:55 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoginSession generated by hbm2java
 */
@Entity
@Table(name = "login_session", catalog = "employee")
public class LoginSession implements java.io.Serializable {

	private LoginSessionId id;
	private EmployeeLogin employeeLogin;
	private String createdBy;
	private Date createdByTime;
	private String updatedBy;
	private Date updatedByTime;
	private Date loginTime;
	private Date logoutTime;
	private String status;

	public LoginSession() {
	}

	public LoginSession(LoginSessionId id, EmployeeLogin employeeLogin, String createdBy, Date createdByTime,
			String updatedBy, Date loginTime, String status) {
		this.id = id;
		this.employeeLogin = employeeLogin;
		this.createdBy = createdBy;
		this.createdByTime = createdByTime;
		this.updatedBy = updatedBy;
		this.loginTime = loginTime;
		this.status = status;
	}

	public LoginSession(LoginSessionId id, EmployeeLogin employeeLogin, String createdBy, Date createdByTime,
			String updatedBy, Date updatedByTime, Date loginTime, Date logoutTime, String status) {
		this.id = id;
		this.employeeLogin = employeeLogin;
		this.createdBy = createdBy;
		this.createdByTime = createdByTime;
		this.updatedBy = updatedBy;
		this.updatedByTime = updatedByTime;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
		this.status = status;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "employeeId", column = @Column(name = "employee_id", nullable = false, length = 50)),
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 50)),
			@AttributeOverride(name = "loginSessionId", column = @Column(name = "login_session_id", nullable = false, length = 30)) })
	public LoginSessionId getId() {
		return this.id;
	}

	public void setId(LoginSessionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "employee_id", referencedColumnName = "username", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "username", referencedColumnName = "employee_id", nullable = false, insertable = false, updatable = false) })
	public EmployeeLogin getEmployeeLogin() {
		return this.employeeLogin;
	}

	public void setEmployeeLogin(EmployeeLogin employeeLogin) {
		this.employeeLogin = employeeLogin;
	}

	@Column(name = "created_by", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_by_time", nullable = false, length = 19)
	public Date getCreatedByTime() {
		return this.createdByTime;
	}

	public void setCreatedByTime(Date createdByTime) {
		this.createdByTime = createdByTime;
	}

	@Column(name = "updated_by", nullable = false, length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_by_time", length = 19)
	public Date getUpdatedByTime() {
		return this.updatedByTime;
	}

	public void setUpdatedByTime(Date updatedByTime) {
		this.updatedByTime = updatedByTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "login_time", nullable = false, length = 19)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logout_time", length = 19)
	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	@Column(name = "status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
