package com.v2soft.training.datamodel;
// Generated Oct 16, 2019 11:18:30 AM by Hibernate Tools 5.1.10.Final

/**
 * EmployeeAddressId generated by hbm2java
 */
public class EmployeeAddressIdMod implements java.io.Serializable {

	private int addressTypeId;
	private String employeeId;

	public EmployeeAddressIdMod() {
	}

	public EmployeeAddressIdMod(int addressTypeId, String employeeId) {
		this.addressTypeId = addressTypeId;
		this.employeeId = employeeId;
	}

	public int getAddressTypeId() {
		return this.addressTypeId;
	}

	public void setAddressTypeId(int addressTypeId) {
		this.addressTypeId = addressTypeId;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeeAddressIdMod))
			return false;
		EmployeeAddressIdMod castOther = (EmployeeAddressIdMod) other;

		return (this.getAddressTypeId() == castOther.getAddressTypeId())
				&& ((this.getEmployeeId() == castOther.getEmployeeId())
						|| (this.getEmployeeId() != null && castOther.getEmployeeId() != null
								&& this.getEmployeeId().equals(castOther.getEmployeeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAddressTypeId();
		result = 37 * result + (getEmployeeId() == null ? 0 : this.getEmployeeId().hashCode());
		return result;
	}

}
