package com.v2soft.training.datamodel;
// Generated Oct 16, 2019 11:18:30 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * EmployeeLogin generated by hbm2java
 */
public class EmployeeLoginMod implements java.io.Serializable {

	private EmployeeLoginIdMod id;
	private EmployeeMod employeeInfo;
	private String password;
	private Set<LoginSessionMod> loginSessions = new HashSet<LoginSessionMod>(0);

	public EmployeeLoginMod() {
	}

	public EmployeeLoginMod(EmployeeLoginIdMod id, EmployeeMod employeeInfo, String password) {
		this.id = id;
		this.employeeInfo = employeeInfo;
		this.password = password;
	}

	public EmployeeLoginMod(EmployeeLoginIdMod id, EmployeeMod employeeInfo, String password,
			Set<LoginSessionMod> loginSessions) {
		this.id = id;
		this.employeeInfo = employeeInfo;
		this.password = password;
		this.loginSessions = loginSessions;
	}

	public EmployeeLoginIdMod getId() {
		return this.id;
	}

	public void setId(EmployeeLoginIdMod id) {
		this.id = id;
	}

	public EmployeeMod getEmployeeInfo() {
		return this.employeeInfo;
	}

	public void setEmployeeInfo(EmployeeMod employeeInfo) {
		this.employeeInfo = employeeInfo;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<LoginSessionMod> getLoginSessions() {
		return this.loginSessions;
	}

	public void setLoginSessions(Set<LoginSessionMod> loginSessions) {
		this.loginSessions = loginSessions;
	}

}
