
package com.v2soft.training.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-10-29T11:05:41.475-04:00
 * Generated source version: 3.3.4
 *
 */
public final class EmployeeForHr_EmployeeForHrPort_Client {

    private static final QName SERVICE_NAME = new QName("http://localhost:8080", "EmployeeForHrService");

    private EmployeeForHr_EmployeeForHrPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EmployeeForHrService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        EmployeeForHrService ss = new EmployeeForHrService(wsdlURL, SERVICE_NAME);
        EmployeeForHr port = ss.getEmployeeForHrPort();

        {
        System.out.println("Invoking createEmployee...");
        com.v2soft.training.client.CreateEmployeeRequestWithSecurity _createEmployee_in = null;
        com.v2soft.training.client.EmployeeWithoutSalary _createEmployee__return = port.createEmployee(_createEmployee_in);
        System.out.println("createEmployee.result=" + _createEmployee__return);


        }

        System.exit(0);
    }

}
