package com.v2soft.training.entities;
// Generated Oct 16, 2019 11:18:55 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmployeeAddressId generated by hbm2java
 */
@Embeddable
public class EmployeeAddressId implements java.io.Serializable {

	private int addressTypeId;
	private String employeeId;

	public EmployeeAddressId() {
	}

	public EmployeeAddressId(int addressTypeId, String employeeId) {
		this.addressTypeId = addressTypeId;
		this.employeeId = employeeId;
	}

	@Column(name = "address_type_id", nullable = false)
	public int getAddressTypeId() {
		return this.addressTypeId;
	}

	public void setAddressTypeId(int addressTypeId) {
		this.addressTypeId = addressTypeId;
	}

	@Column(name = "employee_id", nullable = false, length = 12)
	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeeAddressId))
			return false;
		EmployeeAddressId castOther = (EmployeeAddressId) other;

		return (this.getAddressTypeId() == castOther.getAddressTypeId())
				&& ((this.getEmployeeId() == castOther.getEmployeeId())
						|| (this.getEmployeeId() != null && castOther.getEmployeeId() != null
								&& this.getEmployeeId().equals(castOther.getEmployeeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAddressTypeId();
		result = 37 * result + (getEmployeeId() == null ? 0 : this.getEmployeeId().hashCode());
		return result;
	}

}
