package com.v2soft.training.entities;
// Generated Oct 16, 2019 11:18:55 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * EmployeeInfo generated by hbm2java
 */
@Entity
@Table(name = "employee_info", catalog = "employee", uniqueConstraints = @UniqueConstraint(columnNames = "ssn"))
public class EmployeeInfo implements java.io.Serializable {

	private String employeeId;
	private Date dateOfBirth;
	private String firstName;
	private String lastName;
	private String middleName;
	private String passportNumber;
	private String ssn;
	private Set<EmployeeLogin> employeeLogins = new HashSet<EmployeeLogin>(0);
	private Set<EmployeeAddress> employeeAddresses = new HashSet<EmployeeAddress>(0);

	public EmployeeInfo() {
	}

	public EmployeeInfo(String employeeId, Date dateOfBirth, String firstName, String lastName, String ssn) {
		this.employeeId = employeeId;
		this.dateOfBirth = dateOfBirth;
		this.firstName = firstName;
		this.lastName = lastName;
		this.ssn = ssn;
	}

	public EmployeeInfo(String employeeId, Date dateOfBirth, String firstName, String lastName, String middleName,
			String passportNumber, String ssn, Set<EmployeeLogin> employeeLogins,
			Set<EmployeeAddress> employeeAddresses) {
		this.employeeId = employeeId;
		this.dateOfBirth = dateOfBirth;
		this.firstName = firstName;
		this.lastName = lastName;
		this.middleName = middleName;
		this.passportNumber = passportNumber;
		this.ssn = ssn;
		this.employeeLogins = employeeLogins;
		this.employeeAddresses = employeeAddresses;
	}

	@Id

	@Column(name = "employee_id", unique = true, nullable = false, length = 12)
	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_birth", nullable = false, length = 10)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "first_name", nullable = false, length = 20)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 20)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "middle_name", length = 20)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "passport_number", length = 20)
	public String getPassportNumber() {
		return this.passportNumber;
	}

	public void setPassportNumber(String passportNumber) {
		this.passportNumber = passportNumber;
	}

	@Column(name = "ssn", unique = true, nullable = false, length = 20)
	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeInfo")
	public Set<EmployeeLogin> getEmployeeLogins() {
		return this.employeeLogins;
	}

	public void setEmployeeLogins(Set<EmployeeLogin> employeeLogins) {
		this.employeeLogins = employeeLogins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeInfo")
	public Set<EmployeeAddress> getEmployeeAddresses() {
		return this.employeeAddresses;
	}

	public void setEmployeeAddresses(Set<EmployeeAddress> employeeAddresses) {
		this.employeeAddresses = employeeAddresses;
	}

}
