<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://localhost:8080/types"
	xmlns:tns="http://localhost:8080"
	xmlns:s="http://www.w3.org/2001/XMLSchema"
	xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
	name="EmployeeForHr"
	targetNamespace="http://localhost:8080">
    <types>
		<s:schema elementFormDefault="qualified" targetNamespace="http://localhost:8080/types">
			<s:include schemaLocation="xsd/employee.xsd" />
		</s:schema>
    </types>
    <message name="createEmployeeRequest">
        <part element="xsd:CreateEmployeeRequest" name="in"/>
    </message>
    <message name="createEmployeeResponse">
        <part element="xsd:CreateEmployeeResponse" name="out"/>
    </message>
    <portType name="EmployeeForHr">
        <operation name="createEmployee">
            <input name="createEmployeeRequest" message="tns:createEmployeeRequest"/>
            <output name="createEmployeeResponse" message="tns:createEmployeeResponse"/>
        </operation>
    </portType>
    <binding name="EmployeeForHr_SOAPBinding" type="tns:EmployeeForHr">
        <soap12:binding transport="http://www.w3.org/2003/05/soap/bindings/HTTP/" style="document"/>
        <operation name="createEmployee">
            <soap12:operation style="document" soapAction=""/>
            <input>
                <soap12:body use="literal"/>
            </input>
            <output>
                <soap12:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="EmployeeForHrService">
        <port name="EmployeeForHrPort" binding="tns:EmployeeForHr_SOAPBinding">
            <soap12:address location="http://localhost:8080/EmployeeForHr"/>
        </port>
    </service>
</definitions>
