package com.v2soft.training.noannon;
// Generated Oct 16, 2019 11:18:30 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * EmployeeLogin generated by hbm2java
 */
public class EmployeeLogin implements java.io.Serializable {

	private EmployeeLoginId id;
	private EmployeeInfo employeeInfo;
	private String password;
	private Set<LoginSession> loginSessions = new HashSet<LoginSession>(0);

	public EmployeeLogin() {
	}

	public EmployeeLogin(EmployeeLoginId id, EmployeeInfo employeeInfo, String password) {
		this.id = id;
		this.employeeInfo = employeeInfo;
		this.password = password;
	}

	public EmployeeLogin(EmployeeLoginId id, EmployeeInfo employeeInfo, String password,
			Set<LoginSession> loginSessions) {
		this.id = id;
		this.employeeInfo = employeeInfo;
		this.password = password;
		this.loginSessions = loginSessions;
	}

	public EmployeeLoginId getId() {
		return this.id;
	}

	public void setId(EmployeeLoginId id) {
		this.id = id;
	}

	public EmployeeInfo getEmployeeInfo() {
		return this.employeeInfo;
	}

	public void setEmployeeInfo(EmployeeInfo employeeInfo) {
		this.employeeInfo = employeeInfo;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<LoginSession> getLoginSessions() {
		return this.loginSessions;
	}

	public void setLoginSessions(Set<LoginSession> loginSessions) {
		this.loginSessions = loginSessions;
	}

}
