package com.v2soft.training.noannon;
// Generated Oct 16, 2019 11:18:30 AM by Hibernate Tools 5.1.10.Final

/**
 * LoginSessionId generated by hbm2java
 */
public class LoginSessionId implements java.io.Serializable {

	private String employeeId;
	private String username;
	private String loginSessionId;

	public LoginSessionId() {
	}

	public LoginSessionId(String employeeId, String username, String loginSessionId) {
		this.employeeId = employeeId;
		this.username = username;
		this.loginSessionId = loginSessionId;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getLoginSessionId() {
		return this.loginSessionId;
	}

	public void setLoginSessionId(String loginSessionId) {
		this.loginSessionId = loginSessionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoginSessionId))
			return false;
		LoginSessionId castOther = (LoginSessionId) other;

		return ((this.getEmployeeId() == castOther.getEmployeeId()) || (this.getEmployeeId() != null
				&& castOther.getEmployeeId() != null && this.getEmployeeId().equals(castOther.getEmployeeId())))
				&& ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
						&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getLoginSessionId() == castOther.getLoginSessionId())
						|| (this.getLoginSessionId() != null && castOther.getLoginSessionId() != null
								&& this.getLoginSessionId().equals(castOther.getLoginSessionId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEmployeeId() == null ? 0 : this.getEmployeeId().hashCode());
		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getLoginSessionId() == null ? 0 : this.getLoginSessionId().hashCode());
		return result;
	}

}
