
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.v2soft.training.server;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.BindingType;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2019-10-29T11:06:06.346-04:00
 * Generated source version: 3.3.4
 *
 */

@javax.jws.WebService(
                      serviceName = "EmployeeForHrService",
                      portName = "EmployeeForHrPort",
                      targetNamespace = "http://localhost:8080",
                      //wsdlLocation = "file:/C:/Users/ktrivedi/AppData/Local/Temp/tempdir8546441456257568888.tmp/employee_for_hr_1.wsdl",
                      //wsdlLocation = "file:/C:/Users/ktrivedi/Documents/workspace-spring-training/EmployeeSOAP/My WSDL Code/employee_for_hr.wsdl",
                      endpointInterface = "com.v2soft.training.server.EmployeeForHr")
@BindingType("http://java.sun.com/xml/ns/jaxws/2003/05/soap/bindings/HTTP/")
public class EmployeeForHrPortImpl implements EmployeeForHr {

    private static final Logger LOG = Logger.getLogger(EmployeeForHrPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.v2soft.training.server.EmployeeForHr#createEmployee(com.v2soft.training.server.CreateEmployeeRequestWithSecurity in)*
     */
    public com.v2soft.training.server.EmployeeWithoutSalary createEmployee(CreateEmployeeRequestWithSecurity in) {
        LOG.info("Executing operation createEmployee");
        System.out.println(in);
        //System.out.println(in.getEmployeeWithoutSalary().getFirstName());
        try {
            //com.v2soft.training.server.EmployeeWithoutSalary _return = null;
        	com.v2soft.training.server.EmployeeWithoutSalary _return = in.getEmployeeWithoutSalary();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
