package com.v2soft.training.datamodel;
// Generated Oct 16, 2019 11:18:30 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;

/**
 * LoginSession generated by hbm2java
 */
public class LoginSessionMod implements java.io.Serializable {

	private LoginSessionIdMod id;
	private EmployeeLoginMod employeeLogin;
	private String createdBy;
	private Date createdByTime;
	private String updatedBy;
	private Date updatedByTime;
	private Date loginTime;
	private Date logoutTime;
	private String status;

	public LoginSessionMod() {
	}

	public LoginSessionMod(LoginSessionIdMod id, EmployeeLoginMod employeeLogin, String createdBy, Date createdByTime,
			String updatedBy, Date loginTime, String status) {
		this.id = id;
		this.employeeLogin = employeeLogin;
		this.createdBy = createdBy;
		this.createdByTime = createdByTime;
		this.updatedBy = updatedBy;
		this.loginTime = loginTime;
		this.status = status;
	}

	public LoginSessionMod(LoginSessionIdMod id, EmployeeLoginMod employeeLogin, String createdBy, Date createdByTime,
			String updatedBy, Date updatedByTime, Date loginTime, Date logoutTime, String status) {
		this.id = id;
		this.employeeLogin = employeeLogin;
		this.createdBy = createdBy;
		this.createdByTime = createdByTime;
		this.updatedBy = updatedBy;
		this.updatedByTime = updatedByTime;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
		this.status = status;
	}

	public LoginSessionIdMod getId() {
		return this.id;
	}

	public void setId(LoginSessionIdMod id) {
		this.id = id;
	}

	public EmployeeLoginMod getEmployeeLogin() {
		return this.employeeLogin;
	}

	public void setEmployeeLogin(EmployeeLoginMod employeeLogin) {
		this.employeeLogin = employeeLogin;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedByTime() {
		return this.createdByTime;
	}

	public void setCreatedByTime(Date createdByTime) {
		this.createdByTime = createdByTime;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedByTime() {
		return this.updatedByTime;
	}

	public void setUpdatedByTime(Date updatedByTime) {
		this.updatedByTime = updatedByTime;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
